[package]
name = "jsonata_js_bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
jsonata_rust = { package = "async_jsonata_rust", path = "../../jsonata-rust" }
napi = { version = "3.3", default-features = false, features = ["napi6", "serde-json", "tokio_rt"] }
napi-derive = "3.2"
serde_json = "1.0"
futures = "0.3"
paste = "1.0"
regex = "1.11"

[build-dependencies]
cargo-outdated = "0.17"
napi-build = "2.2"
